# Generated by Django 5.1.2 on 2024-11-30 20:22

import payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, default=payroll.models.generate_employee_code, max_length=10, unique=True),
        ),
    ]
