# Generated by Django 5.1.2 on 2024-12-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_employee_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutrequest',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee'),
        ),
    ]
