# Generated by Django 5.1.2 on 2024-12-01 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_payoutrequest_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouthistory',
            name='payout_request',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payroll.payoutrequest'),
            preserve_default=False,
        ),
    ]
