# Generated by Django 5.1.2 on 2024-12-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payouthistory_payout_request'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payouthistory',
            unique_together={('employee', 'payout_request')},
        ),
    ]
